-- MySQL Workbench Synchronization
-- Generated: 2023-06-22 20:47
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Felipe

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`AUTOR` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biblioteca`.`GENERO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NOT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biblioteca`.`EDITORA` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biblioteca`.`LIVRO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `SLUG` VARCHAR(60) NOT NULL,
  `SINOPSE` TEXT NOT NULL,
  `THUMB` VARCHAR(200) NOT NULL,
  `STATUS` VARCHAR(20) NULL DEFAULT NULL,
  `QTDE` INT(11) NULL DEFAULT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  `GENERO_ID` INT(11) NOT NULL,
  `AUTOR_ID` INT(11) NOT NULL,
  `EDITORA_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_LIVRO_GENERO_idx` (`GENERO_ID` ASC),
  INDEX `fk_LIVRO_AUTOR1_idx` (`AUTOR_ID` ASC),
  INDEX `fk_LIVRO_EDITORA1_idx` (`EDITORA_ID` ASC),
  CONSTRAINT `fk_LIVRO_GENERO`
    FOREIGN KEY (`GENERO_ID`)
    REFERENCES `biblioteca`.`GENERO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_AUTOR1`
    FOREIGN KEY (`AUTOR_ID`)
    REFERENCES `biblioteca`.`AUTOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_EDITORA1`
    FOREIGN KEY (`EDITORA_ID`)
    REFERENCES `biblioteca`.`EDITORA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biblioteca`.`CLIENTE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `CEP` INT(8) NOT NULL,
  `ENDERECO` VARCHAR(45) NOT NULL,
  `CIDADE` VARCHAR(45) NOT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  `NUMERO` INT(11) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `QTDE_EMPRESTIMOS` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biblioteca`.`PEDIDO_LIVRO` (
  `ID_PEDIDO` INT(11) NOT NULL AUTO_INCREMENT,
  `DATA_EMPRESTIMO` DATE NOT NULL,
  `DATA_DEVOLUCAO` DATE NOT NULL,
  `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL,
  `LIVRO_ID` INT(11) NOT NULL,
  `CLIENTE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  INDEX `fk_PEDIDO_LIVRO_LIVRO1_idx` (`LIVRO_ID` ASC),
  INDEX `fk_PEDIDO_LIVRO_CLIENTE1_idx` (`CLIENTE_ID` ASC),
  CONSTRAINT `fk_PEDIDO_LIVRO_LIVRO1`
    FOREIGN KEY (`LIVRO_ID`)
    REFERENCES `biblioteca`.`LIVRO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_LIVRO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `biblioteca`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
