-- MySQL Workbench Synchronization
-- Generated: 2023-06-21 12:33
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Felipe

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `biblioteca`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `biblioteca`.`LIVRO` 
DROP FOREIGN KEY `fk_table1_GENERO`,
DROP FOREIGN KEY `fk_table1_EDITORA1`,
DROP FOREIGN KEY `fk_table1_AUTOR1`;

ALTER TABLE `biblioteca`.`PEDIDO_LIVRO` 
DROP FOREIGN KEY `fk_PEDIDO_LIVRO_CLIENTE1`;

ALTER TABLE `biblioteca`.`AUTOR` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `NOME` `NOME` VARCHAR(45) NOT NULL ;

ALTER TABLE `biblioteca`.`GENERO` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `DESCRICAO` `DESCRICAO` VARCHAR(45) NOT NULL ;

ALTER TABLE `biblioteca`.`EDITORA` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `biblioteca`.`LIVRO` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `TITULO` `TITULO` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `SLUG` `SLUG` VARCHAR(60) NOT NULL ,
CHANGE COLUMN `STATUS` `STATUS` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `D_E_L_E_T_E` `D_E_L_E_T_E` CHAR(1) NULL DEFAULT NULL ,
ADD INDEX `fk_LIVRO_GENERO_idx` (`GENERO_ID` ASC) VISIBLE,
ADD INDEX `fk_LIVRO_AUTOR1_idx` (`AUTOR_ID` ASC) VISIBLE,
ADD INDEX `fk_LIVRO_EDITORA1_idx` (`EDITORA_ID` ASC) VISIBLE,
DROP INDEX `fk_table1_EDITORA1_idx` ,
DROP INDEX `fk_table1_AUTOR1_idx` ,
DROP INDEX `fk_table1_GENERO_idx` ;
;

ALTER TABLE `biblioteca`.`CLIENTE` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
DROP COLUMN `QTDE_LIVRO`,
ADD COLUMN `CEP` INT(8) NOT NULL AFTER `NOME`,
CHANGE COLUMN `NOME` `NOME` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `ENDERECO` `ENDERECO` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `CIDADE` `CIDADE` VARCHAR(45) NOT NULL ;

ALTER TABLE `biblioteca`.`PEDIDO_LIVRO` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `DATA_EMPRESTIMO` `DATA_EMPRESTIMO` DATE NOT NULL ,
CHANGE COLUMN `DATA_DEVOLUCAO` `DATA_DEVOLUCAO` DATE NOT NULL ,
ADD INDEX `fk_PEDIDO_LIVRO_LIVRO1_idx` (`LIVRO_ID` ASC) VISIBLE,
ADD INDEX `fk_PEDIDO_LIVRO_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
DROP INDEX `fk_PEDIDO_LIVRO_CLIENTE1_idx` ,
DROP INDEX `fk_PEDIDO_LIVRO_LIVRO1_idx` ;
;

ALTER TABLE `biblioteca`.`LIVRO` 
ADD CONSTRAINT `fk_LIVRO_GENERO`
  FOREIGN KEY (`GENERO_ID`)
  REFERENCES `biblioteca`.`GENERO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_LIVRO_AUTOR1`
  FOREIGN KEY (`AUTOR_ID`)
  REFERENCES `biblioteca`.`AUTOR` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_LIVRO_EDITORA1`
  FOREIGN KEY (`EDITORA_ID`)
  REFERENCES `biblioteca`.`EDITORA` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `biblioteca`.`PEDIDO_LIVRO` 
DROP FOREIGN KEY `fk_PEDIDO_LIVRO_LIVRO1`;

ALTER TABLE `biblioteca`.`PEDIDO_LIVRO` ADD CONSTRAINT `fk_PEDIDO_LIVRO_LIVRO1`
  FOREIGN KEY (`LIVRO_ID`)
  REFERENCES `biblioteca`.`LIVRO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_PEDIDO_LIVRO_CLIENTE1`
  FOREIGN KEY (`CLIENTE_ID`)
  REFERENCES `biblioteca`.`CLIENTE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
